### PR TITLE
Add xyzrgb dragon

### PR DESCRIPTION
**Pull request by purvigoel**
xyzrgb_dragon.obj is decimated to 250k faces to fit the ~10MB limit. 
xyzrgb_dragon.zip is the original mesh downloaded from the Stanford 3D Scanning repository.

### CODE REVIEW

**Comment by alecjacobson** [comment]
I've been using multiparty zips to keep the originals in their raw state.

**Comment by purvigoel** [comment]
Okay! Is this for the .obj files (the ones that should be either full resolution or at minimum 100k faces), or the original .zip files?

**Comment by alecjacobson** [comment]
I try to keep the .obj below 100k faces and "clean". For the "original"
then I try to retain the most raw data available, splitting into multi-part
zip if need be.

**Comment by purvigoel** [comment]
Got it, thanks for the clarification! So the xyzrgb_dragon.zip file contains the original raw .ply file downloaded from the Stanford scanning repository (~7M faces). I double-checked that none of this information was lost in the compression, so I believe the raw data was retained.

**Comment by purvigoel** [comment]
Ah got it, thanks for the clarification! So the xyzrgb_dragon.zip file contains the original raw .ply file downloaded from the Stanford scanning repository (~7M faces). I double-checked that none of this information was lost in the compression, so I believe the raw data was retained.

**Comment by alecjacobson** [comment]
thanks

**Pull request merged**
